export const COMMON_PASSWORDS: readonly string[] = [
  'password', '123456', '12345678', '123456789', '1234567890',
  'qwerty', 'abc123', 'letmein', 'welcome', 'monkey',
  'dragon', 'master', 'hunter', 'starwars', 'shadow',
  'passw0rd', 'password1', 'iloveyou', 'trustno1', 'sunshine',
  'princess', 'football', 'baseball', 'batman', 'superman',
  'michael', 'ashley', 'bailey', 'jennifer', 'jessica',
  'matthew', 'andrew', 'joshua', 'thomas', 'charlie',
  'martin', 'william', 'joseph', 'daniel', 'nicholas',
  'royal', 'maverick', 'midnight', 'pepper', 'chester',
  'thunder', 'tigger', 'lovely', 'nintendo', 'gangster',
  'flower', 'butterfly', 'rainbow', 'chocolate', 'mustang',
  'fluffy', 'harley', 'jordan', 'qwerty123', 'password123',
  'hello', 'admin', 'root', 'test', 'guest',
  'pass', 'passwd', 'changeme', 'default', 'temp',
  'access', 'secret', '1234', '12345', '1234567',
  '12345678910', 'qwertyuiop', 'asdfghjkl', 'zxcvbnm',
  'qwerty1', 'qwerty12345', '1q2w3e4r', '123qwe', 'qwe123',
  '1qaz2wsx', 'zaqxswcde', 'abc', 'abcd', 'abcde',
  'abcdef', 'abcdefg', 'passw0rd', 'p@ssword', 'p@ssw0rd',
  'admin123', 'adm1n', 'letmein123', 'welcome1', 'w3lc0me',
  'monkey123', 'dragon1', 'master123', 'shadow123', 'sunshine1',
  'football1', 'baseball1', 'batman1', 'superman1',
  'trustno1', 'iloveyou1', 'princess1', 'password!', '123456!',
  'chang3m3', 't3mp0rary', 'pass123', 'pass1234', 'mypass',
  'mypassword', 'mypass123', 'test123', 'test1234', 'hello123',
  'helloworld', 'goodluck', 'havefun', 'nevermind', 'whatever',
  'nothing', 'something', 'anything', 'everything', 'nobody',
  'somebody', 'anybody', 'everybody', 'nothing123', 'something1',
  '123abc', 'abc123456', '123456abc', 'a123456', 'a12345',
  '123qweasd', '1q2w3e4r5t', 'qwerty123456', 'asdfgh123',
  'zxcvbn123', 'pass4321', 'passpass', 'testtest', 'adminadmin',
  'winter', 'summer', 'spring', 'autumn', 'fall',
  'january', 'february', 'march', 'april', 'may',
  'june', 'july', 'august', 'september', 'october',
  'november', 'december', 'monday', 'tuesday', 'wednesday',
  'thursday', 'friday', 'saturday', 'sunday',
  'redsox', 'yankees', 'cowboys', 'packers', 'patriots',
  'steelers', 'giants', 'eagles', 'raiders', '49ers',
  'lakers', 'celtics', 'bulls', 'warriors', 'heat',
  'cubs', 'cardinals', 'dodgers', 'yankees1', 'redsox1',
  'arsenal', 'chelsea', 'liverpool', 'manchester', 'united',
  'barcelona', 'realmadrid', 'juventus', 'bayern', 'acmilan',
  'fender', 'gibson', 'lespaul', 'stratocaster', 'telecaster',
  'metallica', 'nirvana', 'beatles', 'rolling', 'stones',
  'acdc', 'ledzeppelin', 'pinkfloyd', 'eaglesband', 'queen',
  'cookies', 'chocolate1', 'candy', 'cupcake', 'muffin',
  'pizza', 'burger', 'sushi', 'steak', 'bacon',
  'coffee', 'latte', 'espresso', 'mocha', 'beer',
  'wine', 'whiskey', 'vodka', 'tequila', 'rum',
  'kitten', 'puppy', 'bunny', 'hamster', 'parrot',
  'turtle', 'goldfish', 'dolphin', 'penguin', 'eagle',
  'lion', 'tiger', 'bear', 'wolf', 'shark',
  'falcon', 'hawk', 'raven', 'phoenix', 'dragon1',
  'starwars1', 'jedi', 'lightsaber', 'darth', 'vader',
  'yoda', 'chewbacca', 'hansolo', 'r2d2', 'c3po',
  'trek', 'enterprise', 'voyager', 'kirk', 'picard',
  'spock', 'warp', 'trekkie', 'captain', 'commander',
];
